#!/usr/bin/env python3.11

import fileinput

total = 0
with fileinput.input() as f:
    for r in f.readline().rstrip("\n").split(","):
        start, end = r.split("-")
        for id in list(range(int(start), int(end) + 1)):
            sid = str(id)
            mid = len(sid) // 2
            left, right = sid[:mid], sid[mid:]
            if left == right:
                total += id

print(total) # 41294979841
