#!/usr/bin/env python3.11

import fileinput
import re

re = re.compile("^(\\d+)\\1{1,}$") # \1 becomes \x01
total = 0
with fileinput.input() as f:
    for r in f.readline().rstrip("\n").split(","):
        start, end = r.split("-")
        for id in list(range(int(start), int(end) + 1)):
            sid = str(id)
            if re.match(sid):
                total += id

print(total) # 66500947346
