#!/usr/bin/env python3.11

import array as arr
import fileinput

total = 0

with fileinput.input() as f:
    for line in f:
        digits = arr.array("i", [int(n) for n in list(line.rstrip("\n"))])

        p1 = digits.index(max(digits))

        # if the maximum digit is the last digit, re-do without it
        if p1 == len(digits) - 1:
            fixup = digits[:p1]
            p1 = digits.index(max(fixup))

        p2 = digits.index(max(digits[p1+1:]))

        j = 10*digits[p1] + digits[p2]
        total += j

print(total) # 17403
