#!/usr/bin/env python3.11

import fileinput
import re
from collections import deque

LINE_RE = re.compile(r"^(\w+): (.+)$")

map = {}

with fileinput.input() as f:
    lines = [ line.rstrip("\n") for line in f]
    for line in lines:
        src, dests = LINE_RE.search(line).groups()
        map[src] = set(dests.split(" "))

seen = set()
queue = deque([("you",)])

outs = 0
while queue:
    path = queue.pop()
    here = path[-1]

    if path not in seen:
        seen.add(path)
        for next in map[here]:
            if next == "out":
                outs += 1
                continue
            queue.append((*path, next))

print(outs) # 749
