#!/usr/bin/env python3.11

import fileinput
from itertools import groupby

import pprint

with fileinput.input() as f:
    # would be easier with regular file.read?
    parts = [list(part) for key, part in groupby(f, key=lambda x: x != '\n') if key]
    _ranges, _ids = [[line.rstrip("\n") for line in part] for part in parts ]

ranges = []
for r in _ranges:
    start, end = r.split("-")
    ranges.append(range(int(start), int(end)))

ranges = sorted(ranges, key=lambda r: r.start)
ranges.reverse()

coalesced = []

last = ranges.pop()
while len(ranges) > 0:
    this = ranges.pop()

    if last.stop < this.start:
        coalesced.append(last)
        last = this

    else:
        last = range(min(last.start,this.start), max(last.stop, this.stop))

coalesced.append(last) # drops out of the loop unprocessed

total = 0
for c in coalesced:
    total += (c.stop + 1) - c. start

print(total) # 358155203664116
