#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.11"
# dependencies = [
#  "scipy"
# ]
# ///

import fileinput
import math
from itertools import combinations

from scipy.cluster.hierarchy import DisjointSet

boxes = []

with fileinput.input() as f:
    for line in f:
        x, y, z = [ int(c) for c in line.rstrip("\n").split(",") ]
        boxes.append((x, y, z))

def dist(key: set) -> int:
    """Pythagoras distance^2."""
    return(math.dist(*key))

edges = sorted(combinations(boxes, 2), key=dist)

djs = DisjointSet(boxes)

for pair in edges[:1000]: # or :10 for the example
    djs.merge(*pair)

lengths = [len(ss) for ss in djs.subsets()]
lengths.sort(reverse=True)

print(math.prod(lengths[:3])) # 75582

# ruff: noqa: ERA001
# vim: ft=python
