#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.11"
# dependencies = [
#  "scipy"
# ]
# ///

import fileinput
import pprint
from scipy.cluster.hierarchy import DisjointSet
from itertools import combinations
from math import prod

boxes = []
with fileinput.input() as f:
    for line in f:
        x, y, z = [ int(c) for c in line.rstrip("\n").split(",") ]
        boxes.append((x, y, z))

def dist(key):
    j1, j2 = key
    x1, y1, z1 = j1
    x2, y2, z2 = j2
    return((x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2)

sorted = sorted(combinations(boxes, 2), key=dist)

djs = DisjointSet(boxes)

for index, pair in enumerate(sorted):
    djs.merge(*pair)
    if len(djs.subsets()) == 1:
        print(prod(p[0] for p in pair)) # 59039696
        break

# vim: ft=python
